name: Terraform IaC Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/env/prod/**'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'terraform/env/prod/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform_vpc:
    name: 'VPC Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/env/prod/vpc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out plan.out

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' 
        run: terraform apply "plan.out"
  terraform_eks:
    name: "EKS Terraform"
    needs: terraform_vpc
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/env/prod/eks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out plan.out

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' 
        run: terraform apply "plan.out"